#!/usr/bin/env bash
# Pull latest code from GitHub and restart the bot.
# Run as tomcat user (uses sudo only for systemctl).
# Manual:   /home/tomcat/deploy.sh
# Auto:     fired by tomcat-deploy.timer at 5am daily.
#
# Install:  cp deploy/deploy.sh /home/tomcat/deploy.sh && chmod +x /home/tomcat/deploy.sh
#
# This script must never destroy runtime state. It previously ran
# `git reset --hard origin/main`, which silently reverted tracked-but-live data
# files ("TomCatBot Pics.csv" and the feeding ndjson) to whatever was last
# committed -- months stale. Those files are untracked now, and the update step
# below refuses rather than overwrites, so a dirty tree aborts the deploy
# instead of losing data.

set -euo pipefail

REPO_DIR=/home/tomcat/PyTomCat
VENV_PIP=$REPO_DIR/.venv/bin/pip
REQ_FILE=$REPO_DIR/requirements-droplet.txt
BACKUP_DIR=/home/tomcat/backups/runtime
KEEP_BACKUPS=14
TS=$(date -Iseconds)

# Runtime state with no other local backup. The photo metadata CSV is mirrored
# to Google Sheets every few minutes, but the feeding files are not mirrored
# anywhere, so this tarball is their only copy.
RUNTIME_PATHS=(
  "TomCatBot Pics.csv"
  "cache/feeding_checklist.ndjson"
  "cache/feeding_schedule.ndjson"
  "cache/catabase/profiles.json"
)

cd "$REPO_DIR"

# If we fail after stopping the bot, bring it back rather than leaving it down.
STOPPED=0
on_exit() {
  local rc=$?
  if [ "$rc" -ne 0 ] && [ "$STOPPED" = "1" ]; then
    echo "[deploy $TS] FAILED (exit $rc) - restarting tomcat so the bot is not left down"
    sudo systemctl start tomcat || true
  fi
  exit "$rc"
}
trap on_exit EXIT

echo "[deploy $TS] Checking for updates"

git fetch --quiet origin main
LOCAL=$(git rev-parse HEAD)
REMOTE=$(git rev-parse origin/main)

if [ "$LOCAL" = "$REMOTE" ]; then
  echo "[deploy $TS] Already up to date at ${LOCAL:0:7}"
  exit 0
fi

# Verify the update is a clean fast-forward BEFORE touching the running bot, so
# a diverged or dirty checkout costs no downtime.
if ! git merge-base --is-ancestor HEAD origin/main; then
  echo "[deploy $TS] ERROR: HEAD is not an ancestor of origin/main (diverged)."
  echo "[deploy $TS] Refusing to deploy. Resolve by hand; the bot is untouched."
  exit 1
fi

echo "[deploy $TS] Updating ${LOCAL:0:7} -> ${REMOTE:0:7}"

# Back up runtime state before any repo operation.
mkdir -p "$BACKUP_DIR"
BACKUP_FILE="$BACKUP_DIR/runtime-$(date +%Y%m%d-%H%M%S).tgz"
EXISTING=()
for path in "${RUNTIME_PATHS[@]}"; do
  [ -e "$path" ] && EXISTING+=("$path")
done
if [ ${#EXISTING[@]} -gt 0 ]; then
  tar -czf "$BACKUP_FILE" -C "$REPO_DIR" "${EXISTING[@]}"
  echo "[deploy $TS] Backed up ${#EXISTING[@]} runtime file(s) -> $BACKUP_FILE"
  # Keep only the most recent KEEP_BACKUPS archives.
  ls -1t "$BACKUP_DIR"/runtime-*.tgz 2>/dev/null | tail -n +$((KEEP_BACKUPS + 1)) | xargs -r rm -f
else
  echo "[deploy $TS] WARNING: no runtime files found to back up"
fi

# Detect if requirements changed before updating.
REQ_CHANGED=0
if ! git diff --quiet "$LOCAL" "$REMOTE" -- "$REQ_FILE" 2>/dev/null; then
  REQ_CHANGED=1
fi

sudo systemctl stop tomcat || true
STOPPED=1

# --ff-only refuses if the tree cannot cleanly fast-forward. Unlike
# `reset --hard` it will not discard local modifications to tracked files.
git merge --ff-only origin/main

if [ "$REQ_CHANGED" = "1" ] || [ ! -f "$REQ_FILE" ]; then
  echo "[deploy $TS] Requirements changed - running pip install"
  "$VENV_PIP" install -r "$REQ_FILE"
else
  echo "[deploy $TS] Requirements unchanged - skipping pip install"
fi

sudo systemctl start tomcat
STOPPED=0
echo "[deploy $TS] Started tomcat.service"

# Pick up any config.yml ingress changes regenerated by start.py on restart.
# The tunnel runs as its own supervised unit (deploy/cloudflared.service);
# restarting it is best-effort and must not fail the deploy.
sudo systemctl restart cloudflared || true
echo "[deploy $TS] Restarted cloudflared.service"
